# @Author       : Ruopeng Gao
# @Date         : 2022/7/5
# @Description  : Config for ResNet18 and MNIST.

# RULES:
# The name of the key should be unique.

MODE: # "train" or "eval", for the main.py script.
DEVICE: cuda
AVAILABLE_GPUS: 0,1,2,3,4,5,6,7
#GPUS: [0, 1, 2, 3, 4, 5, 6, 7]

DATA:
  DATASET: MNIST
  DATA_PATH: ./dataset/MNIST/
  CLASS_NUM: 10
  NUM_WORKERS: 0

MODEL:
  PRETRAINED:

TRAIN:
  LR: 0.0001
  BATCH_SIZE: 32
  EPOCHS: 10
  RESUME:
    RESUME_MODEL:
    START_EPOCH:
    CHECKPOINT_OPTIM_STATE: True
  SCHEDULER:
    MILESTONES: [6, 8]
    GAMMA: 0.5

EVAL:
  EVAL_MODEL:

OUTPUTS:
  OUTPUTS_DIR: ./outputs/

DISTRIBUTED:
  USE_DISTRIBUTED: False

