# @Author       : Ruopeng Gao
# @Date         : 2022/7/5
# @Description  : Config for ResNet18 and MNIST.

# RULES:
# The name of the key should be unique.

MODE: # "train" or "eval", for the main.py script.
DEVICE: mps

DATA:
  DATASET: MNIST
  DATA_PATH: ./datasets/
  CLASS_NUM: 10

MODEL:
  PRETRAINED:

TRAIN:
  LR:
  BATCH_SIZE: 8
  EPOCHS: 20

EVAL:
  EVAL_MODEL:

OUTPUTS:
  OUTPUTS_DIR: ./outputs/

